AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Tech Challenge 4 - Processador de Eventos e Notificação (Assíncrono)

Globals:
  Function:
    Timeout: 30
    MemorySize: 256
    Architectures:
      - x86_64

Parameters:
  DynamoDbTableName:
    Type: String
    Default: Feedbacks
  AdminEmail:
    Type: String
    Default: gustavo.jog+admin@hotmail.com
  SourceEmail:
    Type: String
    Default: gustavo.jog+no-reply@hotmail.com
  
  # NOMES EXATOS DAS SUAS FILAS EXISTENTES NA AWS (Criadas manualmente)
  QueueNameMain:
    Type: String
    Default: FeedbackSubmittedQueue
  QueueNameDLQ:
    Type: String
    Default: FeedbackFailedQueue

Resources:

  # ---------------------------------------------------------
  # CONSUMER LAMBDA (Processa mensagens da Fila)
  # ---------------------------------------------------------
  NotificationProcessorFunction:
    Type: AWS::Serverless::Function
    Properties:
      # REMOVIDO FunctionName FIXO PARA EVITAR CONFLITO DE DEPLOY
      Description: Processa mensagens da fila existente e envia notificações.
      PackageType: Image

      Events:
        SQSTrigger:
          Type: SQS
          Properties:
            # Conecta na fila MAIN existente via ARN montado dinamicamente
            Queue: !Sub "arn:aws:sqs:${AWS::Region}:${AWS::AccountId}:${QueueNameMain}"
            BatchSize: 1
      
      Environment:
        Variables:
          QUARKUS_LOG_LEVEL: INFO
          EMAIL_ADMIN_ADDRESS: !Ref AdminEmail
          EMAIL_SOURCE_ADDRESS: !Ref SourceEmail
          FEEDBACK_DYNAMODB_TABLE_NAME: !Ref DynamoDbTableName
      
      Policies:
        - Statement:
            # 1. Permissão na Fila Principal
            - Effect: Allow
              Action:
                - sqs:ReceiveMessage
                - sqs:DeleteMessage
                - sqs:GetQueueAttributes
              Resource: !Sub "arn:aws:sqs:${AWS::Region}:${AWS::AccountId}:${QueueNameMain}"
            
            # 2. Permissão na DLQ
            - Effect: Allow
              Action:
                - sqs:GetQueueAttributes
                - sqs:SendMessage
              Resource: !Sub "arn:aws:sqs:${AWS::Region}:${AWS::AccountId}:${QueueNameDLQ}"

            # 3. DynamoDB
            - Effect: Allow
              Action:
                - dynamodb:GetItem
                - dynamodb:PutItem
              Resource: !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${DynamoDbTableName}"
            
            # 4. SES e Logs
            - Effect: Allow
              Action: ses:SendEmail
              Resource: '*'
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource: '*'

    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./feedback-notification-processor
      DockerTag: v1

  # ---------------------------------------------------------
  # API GATEWAY (HTTP API)
  # ---------------------------------------------------------
  FeedbackApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      CorsConfiguration:
        AllowOrigins:
          - "*"
        AllowMethods:
          - GET
          - POST
          - OPTIONS
        AllowHeaders:
          - "Content-Type"
          - "Authorization"
      Auth:
        DefaultAuthorizer: CognitoJwtAuthorizer
        Authorizers:
          CognitoJwtAuthorizer:
            IdentitySource: "$request.header.Authorization"
            JwtConfiguration:
              issuer: !Sub "https://cognito-idp.${AWS::Region}.amazonaws.com/${FeedbackUserPool}"
              audience:
                - !Ref FeedbackUserPoolClient
      DefaultRouteSettings:
        ThrottlingBurstLimit: 20
        ThrottlingRateLimit: 10

  # ---------------------------------------------------------
  # PRODUCER LAMBDA (Recebe HTTP e manda para Fila)
  # ---------------------------------------------------------
  FeedbackIngestionFunction:
    Type: AWS::Serverless::Function
    Properties:
      # REMOVIDO FunctionName FIXO PARA EVITAR CONFLITO DE DEPLOY
      Description: API de ingestão de feedbacks (HTTP) -> DynamoDB + SQS.
      PackageType: Image
      Events:
        ApiPost:
          Type: HttpApi
          Properties:
            ApiId: !Ref FeedbackApi
            Path: /avaliacao
            Method: POST
      Environment:
        Variables:
          QUARKUS_LOG_LEVEL: INFO
          FEEDBACK_DYNAMODB_TABLE_NAME: !Ref DynamoDbTableName
          # Monta a URL da fila (Necessária para o Producer)
          FEEDBACK_SUBMITTED_QUEUE_URL: !Sub "https://sqs.${AWS::Region}.amazonaws.com/${AWS::AccountId}/${QueueNameMain}"
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - dynamodb:PutItem
              Resource: !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${DynamoDbTableName}"
            - Effect: Allow
              Action:
                - sqs:SendMessage
              # Monta o ARN da fila (Necessário para a Permissão)
              Resource: !Sub "arn:aws:sqs:${AWS::Region}:${AWS::AccountId}:${QueueNameMain}"
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource: '*'
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./feedback-ingestion-api
      DockerTag: v1

  # ---------------------------------------------------------
  # COGNITO (Autenticação)
  # ---------------------------------------------------------
  FeedbackUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: FeedbackUsers
      AutoVerifiedAttributes: [ email ]
      UsernameAttributes: [ email ]

  FeedbackUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: FeedbackAppClient
      UserPoolId: !Ref FeedbackUserPool
      GenerateSecret: false
      ExplicitAuthFlows:
        - ALLOW_USER_PASSWORD_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
        - ALLOW_ADMIN_USER_PASSWORD_AUTH

Outputs:
  NotificationProcessorFunctionArn:
    Description: ARN da função Lambda Consumer
    Value: !GetAtt NotificationProcessorFunction.Arn
  FeedbackIngestionFunctionArn:
    Description: ARN da função Lambda Producer
    Value: !GetAtt FeedbackIngestionFunction.Arn
  FeedbackApiEndpoint:
    Description: Endpoint base da API de Ingestão (HttpApi)
    Value: !Sub "https://${FeedbackApi}.execute-api.${AWS::Region}.amazonaws.com"
  CognitoUserPoolId:
    Description: ID do User Pool do Cognito
    Value: !Ref FeedbackUserPool
  CognitoClientId:
    Description: ID do App Client do Cognito
    Value: !Ref FeedbackUserPoolClient