AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Tech Challenge 4 - Processador e Ingestão (Conecta em recursos existentes)

Globals:
  Function:
    Timeout: 30
    MemorySize: 256
    Architectures:
      - x86_64

Parameters:
  DynamoDbTableName:
    Type: String
    Default: Feedbacks
  AdminEmail:
    Type: String
    Default: jeferson.herculano@outlook.com
  SourceEmail:
    Type: String
    Default: jh93.dev@gmail.com
  
  # NOMES DAS FILAS EXISTENTES NA AWS
  QueueNameMain:
    Type: String
    Default: FeedbackSubmittedQueue
  QueueNameDLQ:
    Type: String
    Default: FeedbackFailedQueue

Resources:

  # --- PROCESSADOR DE NOTIFICAÇÕES (Consumer) ---
  NotificationProcessorFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: NotificationProcessorFunction
      Description: Processa mensagens da fila existente.
      PackageType: Image

      Events:
        SQSTrigger:
          Type: SQS
          Properties:
            # Conecta na fila MAIN existente
            Queue: !Sub "arn:aws:sqs:${AWS::Region}:${AWS::AccountId}:${QueueNameMain}"
            BatchSize: 1
      
      Environment:
        Variables:
          QUARKUS_LOG_LEVEL: INFO
          EMAIL_ADMIN_ADDRESS: !Ref AdminEmail
          EMAIL_SOURCE_ADDRESS: !Ref SourceEmail
          FEEDBACK_DYNAMODB_TABLE_NAME: !Ref DynamoDbTableName
      
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - sqs:ReceiveMessage
                - sqs:DeleteMessage
                - sqs:GetQueueAttributes
              Resource: !Sub "arn:aws:sqs:${AWS::Region}:${AWS::AccountId}:${QueueNameMain}"
            - Effect: Allow
              Action:
                - sqs:GetQueueAttributes
                - sqs:SendMessage
              Resource: !Sub "arn:aws:sqs:${AWS::Region}:${AWS::AccountId}:${QueueNameDLQ}"
            - Effect: Allow
              Action:
                - dynamodb:GetItem
                - dynamodb:PutItem
              Resource: !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${DynamoDbTableName}"
            - Effect: Allow
              Action: ses:SendEmail
              Resource: '*'
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource: '*'
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./feedback-notification-processor
      DockerTag: v1

  # --- API GATEWAY & COGNITO ---
  FeedbackApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      CorsConfiguration:
        AllowOrigins:
          - "*"
        AllowMethods:
          - GET
          - POST
          - OPTIONS
        AllowHeaders:
          - "Content-Type"
          - "Authorization"
      Auth:
        DefaultAuthorizer: CognitoJwtAuthorizer
        Authorizers:
          CognitoJwtAuthorizer:
            IdentitySource: "$request.header.Authorization"
            JwtConfiguration:
              issuer: !Sub "https://cognito-idp.${AWS::Region}.amazonaws.com/${FeedbackUserPool}"
              audience:
                - !Ref FeedbackUserPoolClient
      DefaultRouteSettings:
        ThrottlingBurstLimit: 20
        ThrottlingRateLimit: 10

  # --- FUNÇÃO DE INGESTÃO (Producer) ---
  FeedbackIngestionFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: FeedbackIngestionFunction
      Description: API de ingestão de feedbacks.
      PackageType: Image
      Events:
        ApiPost:
          Type: HttpApi
          Properties:
            ApiId: !Ref FeedbackApi
            Path: /avaliacao
            Method: POST
      Environment:
        Variables:
          QUARKUS_LOG_LEVEL: INFO
          FEEDBACK_DYNAMODB_TABLE_NAME: !Ref DynamoDbTableName
          # CORREÇÃO CRÍTICA: Usar !Sub para montar a URL da fila existente
          FEEDBACK_SUBMITTED_QUEUE_URL: !Sub "https://sqs.${AWS::Region}.amazonaws.com/${AWS::AccountId}/${QueueNameMain}"
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - dynamodb:PutItem
              Resource: !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${DynamoDbTableName}"
            - Effect: Allow
              Action:
                - sqs:SendMessage
              # CORREÇÃO CRÍTICA: Usar !Sub para o ARN da fila existente
              Resource: !Sub "arn:aws:sqs:${AWS::Region}:${AWS::AccountId}:${QueueNameMain}"
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource: '*'
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./feedback-ingestion-api
      DockerTag: v1

  # --- COGNITO RESOURCES ---
  FeedbackUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: FeedbackUsers
      AutoVerifiedAttributes: [ email ]
      UsernameAttributes: [ email ]

  FeedbackUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: FeedbackAppClient
      UserPoolId: !Ref FeedbackUserPool
      GenerateSecret: false
      ExplicitAuthFlows:
        - ALLOW_USER_PASSWORD_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
        - ALLOW_ADMIN_USER_PASSWORD_AUTH

Outputs:
  NotificationProcessorFunctionArn:
    Description: ARN da função Lambda Processor
    Value: !GetAtt NotificationProcessorFunction.Arn
  FeedbackApiEndpoint:
    Description: Endpoint base da API de Ingestão
    Value: !Sub "https://${FeedbackApi}.execute-api.${AWS::Region}.amazonaws.com"
  CognitoUserPoolId:
    Description: ID do User Pool do Cognito
    Value: !Ref FeedbackUserPool
  CognitoClientId:
    Description: ID do App Client do Cognito
    Value: !Ref FeedbackUserPoolClient
    # Removida linha duplicada "Value: ..." que causaria erro de sintaxe
