PDF_DIAS_URL_VALIDA=20
PDF_BUCKET=relatorios-avaliacao-bucket1

# Logging
quarkus.log.console.json=true
quarkus.log.level=INFO

FEEDBACK_DYNAMODB_TABLE_NAME=${FEEDBACK_DYNAMODB_TABLE_NAME:Feedbacks}
EMAIL_ADMIN_ADDRESS=gustavo.jog+admin@hotmail.com
EMAIL_SOURCE_ADDRESS=gustavo.jog+noreply@hotmail.com